// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using restApiDataset.Models;

namespace restApiDataset.Migrations
{
    [DbContext(typeof(OcrDbContext))]
    [Migration("20200826103558_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("BnOcrDatasetApi.Models.OcrTrash", b =>
                {
                    b.Property<long>("OcrTrashId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<long?>("OcrClassId")
                        .HasColumnType("bigint");

                    b.HasKey("OcrTrashId");

                    b.HasIndex("OcrClassId");

                    b.ToTable("OcrTrashes");
                });

            modelBuilder.Entity("restApiDataset.Models.OcrClass", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("ConsonantDiacreticId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FileName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("FontSize")
                        .HasColumnType("int");

                    b.Property<string>("GraphemeRootId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageData")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VowelDiacreticId")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("OcrClasses");
                });

            modelBuilder.Entity("BnOcrDatasetApi.Models.OcrTrash", b =>
                {
                    b.HasOne("restApiDataset.Models.OcrClass", "OcrClass")
                        .WithMany()
                        .HasForeignKey("OcrClassId");
                });
#pragma warning restore 612, 618
        }
    }
}
